name: Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: code

    - name: Install Rsync
      run: sudo apt-get install -y rsync

    - name: Setup SSH 1
      run: mkdir -p ~/.ssh

    - name: Setup SSH 2
      run: ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Setup SSH 3
      run: echo ${{ secrets.SSH_PUB_KEY }} >> ~/.ssh/id_rsa.pub

    - name: Setup SSH 4
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}' >> ~/.ssh/id_rsa

    - name: Setup SSH 5
      run: chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub
    
    - name: Create Dir
      run: ssh root@${{ secrets.SERVER_HOST }} "mkdir -p /root/apps/wechat-bot"

    - name: Sync files
      run: |
        rsync -av --delete --exclude='.*' code/ root@${{ secrets.SERVER_HOST }}:/root/apps/wechat-bot

    - name: Run
      run: ssh root@${{ secrets.SERVER_HOST }} "export IMAGE_TAG=${GITHUB_SHA::4}_$(date +'%Y%m%d') && cd /root/apps/wechat-bot && docker compose up -d"
